### ISSUE TITLE
rush gamemode

### ISSUE THREAD

**Issue by gyeyoqu** [Tyler3D/Multi-Ogar-Edited-Unlimited#10]
title

**Comment by Tyler3D** [comment]
I made one but, the leaderboard doesn't work on vanilla client. Plus, I can't figure out how to find first place

**Comment by gyeyoqu** [comment]
i use my own client

**Comment by Tyler3D** [comment]
@gyeyoqu Ok but the gamemode isn't really working well

**Comment by Tyler3D** [comment]
Ill release I guess then
