### ISSUE TITLE
Error login in Linux

### ISSUE THREAD

**Issue by mafiakb** [Tyler3D/Multi-Ogar-Edited-Unlimited#100]
this error, how fix?

![image](https://cloud.githubusercontent.com/assets/12769609/24565650/be26aee8-161b-11e7-88b3-2969cca783ab.png)

![image](https://cloud.githubusercontent.com/assets/12769609/24565635/a9635d12-161b-11e7-8201-88d0c0fcc349.png)

**Comment by vincent95330** [comment]
for me too
