### ISSUE TITLE
A strange connection to the server

### ISSUE THREAD

**Issue by ToporBigBots** [Tyler3D/Multi-Ogar-Edited-Unlimited#102]
Switch between servers. One of the servers your updated when it is selected, there is a temporary lag i.e. the time everything freezes (2-5 seconds). With other servers this was not. Please fix it, thanks

**Comment by t11tanYT** [comment]
please idi naxyi

**Comment by Tyler3D** [comment]
@ToporBigBots Can you rewrite your issue to the issue template --> https://github.com/Tyler3D/Multi-Ogar-Edited-Unlimited/blob/master/ISSUE_TEMPLATE.md
I don't really understand

**Comment by Logan7432** [comment]
@Tyler3D When I get about 5-10 people on my server it starts to lag very very bad..... I dont think it could be my internet that hosting the server because its 200mbs down and 15mbs up. I'm pretty sure 5-10 people it shouldn't be starting to lag....

**Comment by Logan7432** [comment]
@Tyler3D See for yourself, WIlsonsd12.ooguy.com
