### ISSUE TITLE
How?

### ISSUE THREAD

**Issue by Jhair2015** [Tyler3D/Multi-Ogar-Edited-Unlimited#103]
How to prevent the server from automatically saving or creating a ServerLog, I see that it creates too many .txt files, it makes the server heavier, How?

**Comment by Tyler3D** [comment]
@Jhair2015 It shouldn't lag the server but. you can commit this line ->https://github.com/Tyler3D/Multi-Ogar-Edited-Unlimited/blob/master/src/modules/Logger.js#L217

**Comment by Jhair2015** [comment]
@Tyler3D Thanks
