### ISSUE TITLE
Commands/other

### ISSUE THREAD

**Issue by Logan7432** [Tyler3D/Multi-Ogar-Edited-Unlimited#104]
For my server the MiniMap is way out of sync with the server. Is there a way to change the code and implement the map code that cigar uses? My client is in sync with the cigar server but not this one. https://ibb.co/gou9dv

**Comment by Logan7432** [comment]
Also, I don't wanna make a new issue form but can you make it so the admin has more commands? Like I Do /addbot (number) but then when I try and remove bots by doing /kickbot  (number) it says unknown command which what most of the commands I type in say

**Comment by Logan7432** [comment]
Never mind about Mini-Map I fixed it. But Please fix second one.

**Comment by vincent95330** [comment]
@Logan7432 Use this script : 

function drawMap() {
        if (playerCells.length == 0) return;
        ctx.save();

        function gcd(a, b) {
            return !b ? a : gcd(b, a % b);
        }
        ctx.beginPath();
        ctx.fillStyle = "rgba(0,0,0,.50)";
        var size = 200;
        ctx.lineWidth = 1.5;
        var mapX = canvasWidth - size - 10;
        var mapY = canvasHeight - size - 10;
        ctx.rect(mapX, mapY, size, size);
        ctx.fill();

        var newX = nodeX / (rightPos - leftPos);
        var newY = nodeY / (bottomPos - topPos);
        var posX = (newX * size + mapX) + size / 2;
        var posY = (newY * size + mapY) + size / 2;
        var bw = bh = size;
        var insideX = -1;
        var insideY = -1;
        for (var x = 0; x <= bw; x += 40) {
            if (x != bw) {
                var ix = 0.5 + x + mapX;
                var iy = mapY;
                if (insideBox(ix, iy, ix + 40, iy + bh, posX, posY)) {
                    insideX = ix;
                }
                if (x == 0) continue;

            }
            ctx.fillStyle = "white";
            ctx.font = "900 18px Ubuntu";
            ctx.textAlign = "center";
            ctx.strokeStyle = "white";
            ctx.lineWidth = 1;
            ctx.globalAlpha = 0.35;
            for (var i = 0; i < 5; i++) {
                ctx.fillText(String.fromCharCode(i + 65) + x / 40, (0.5 + x + mapX) - 20, mapY + 25.5 + (i * 40));
            }
        }
        for (var y = 0; y <= bh; y += 40) {
            if (y != bh) {
                var ix = mapX;
                var iy = 0.5 + y + mapY;
                if (insideBox(ix, iy, ix + bw, iy + 40, posX, posY)) {
                    insideY = iy;
                }
                if (y == 0) continue;

            }
        }
        if (playerCells.length > 0 && insideX > -1 && insideY > -1) {
            ctx.fillStyle = "#000";
            ctx.globalAlpha = 0.3;
            ctx.fillRect(insideX, insideY, 40, 40);
        }
        ctx.globalAlpha = 1;
        ctx.strokeStyle = "rgba(255,255,255,.2)";
        ctx.stroke();
        ctx.closePath();
   
            var player = playerCells[0];
            var ox = playerX / (rightPos - leftPos);
            var oy = playerY / (bottomPos - topPos);
            var x = (ox * size + mapX) + size / 0;
            var y = (oy * size + mapY) + size / 0;
            var mass = Math.max(2, 400 / (size / 0));
            if (i == 0) {
                ctx.font = "bold " + (14 + mass) + "px Ubuntu";
                var measure = ctx.measureText(player.name);
                ctx.strokestyle = "black";
            }
            ctx.beginPath();
            ctx.strokeStyle = 'black';
            ctx.lineWidth = 1;
            ctx.globalAlpha = 1;
            ctx.arc(x, y, mass, 0, 2 * Math.PI);
            ctx.stroke();
            ctx.fill();
            ctx.closePath();
        
        ctx.restore();
    };

**Comment by Logan7432** [comment]
@vincent95330 Thanks!

**Comment by Logan7432** [comment]
@vincent95330 Thanks! Hey, just a question. Do you know how to fix the leader board plugin? Or remove the this line of text that appears in the chat? https://ibb.co/ix1YbF
