### ISSUE TITLE
Create account 

### ISSUE THREAD

**Issue by vincent95330** [Tyler3D/Multi-Ogar-Edited-Unlimited#106]
Why i can't create account in linux ?

**Comment by Logan7432** [comment]
Should be fixed from last commit, try and update server

**Comment by vincent95330** [comment]
@Logan7432 thx i will try ..

**Comment by vincent95330** [comment]
No, now i can't create account and server crashing ....

**Comment by Logan7432** [comment]
@vincent95330 Weird

**Comment by Tyler3D** [comment]
@vincent95330 Follow the issue template -> https://github.com/Tyler3D/Multi-Ogar-Edited-Unlimited/blob/master/ISSUE_TEMPLATE.md
I can't help you if you don't give me information
I'll close for now
