### ISSUE TITLE
How to fix?

### ISSUE THREAD

**Issue by Wair1o17** [Tyler3D/Multi-Ogar-Edited-Unlimited#109]
![image](https://cloud.githubusercontent.com/assets/18153674/24731414/7eea640a-1a2f-11e7-8387-3dd4044ffcd4.png)

**Comment by FlareYT** [comment]
There is something wrong with the Variable getName.
I suggest you to reinstall the Files and try it again :)

~ Flare

**Comment by Wair1o17** [comment]
@FlareYT Fixed 1 month ago :p
