### ISSUE TITLE
Auto restart

### ISSUE THREAD

**Issue by vincent95330** [Tyler3D/Multi-Ogar-Edited-Unlimited#110]
Can you make autoRestart with max mass in server ? Thx :)

**Comment by Jhair2015** [comment]
Yes, @Tyler3D  that would be great :)

**Comment by AGarRiBiA** [comment]
:+1: yes

**Comment by Tyler3D** [comment]
This already exists

**Comment by AGarRiBiA** [comment]
@Tyler3D how ?

**Comment by Wair1o17** [comment]
@vincent95330 Can you help me with aws, open ports and it pls??
