### ISSUE TITLE
Protocal

### ISSUE THREAD

**Issue by Logan7432** [Tyler3D/Multi-Ogar-Edited-Unlimited#113]
How do I remove the line of text that appears in the chat that says WARNING: Protocol 1 assumed as 4?

**Comment by Jhair2015** [comment]
Control + F on MultiOgar [Gameserver.js]

**Comment by Tyler3D** [comment]
^^

**Comment by Logan7432** [comment]
@Jhair2015 @Tyler3D What? I Don't understand this.

**Comment by alktbihd** [comment]
@Logan7432 you need to get a compatible client

**Comment by Jhair2015** [comment]
@alktbihd Yes you are right, @Logan7432 You client is protocol old [PROTOCOL 1] or just search on Gameserver.js 'Protocol 1' and changue the text

**Comment by Logan7432** [comment]
@Jhair2015 Is that bad if its on protocol 1? And if so how do i update to newest.

**Comment by Jhair2015** [comment]
@Logan7432 Cigar

**Comment by Logan7432** [comment]
@Jhair2015 If i were to update it to cigar would i replace the main_out?

**Comment by Jhair2015** [comment]
@Logan7432 idk much about cigar lol

**Comment by Mr-BrockLee** [comment]
@Jhair2015 What client do you use?

**Comment by Logan7432** [comment]
@Jhair2015 Could you help me update my current client to newest protocol?

**Comment by Logan7432** [comment]
I think i just fixed it. Can someone explain to me what protocol is though?
