### ISSUE TITLE
hosting

### ISSUE THREAD

**Issue by Logan7432** [Tyler3D/Multi-Ogar-Edited-Unlimited#116]
Any hosting website for servers like this you guys know of?

**Comment by Jhair2015** [comment]
Hostinger, BanaHosting, 000webhost, godaddy, etc...

**Comment by alktbihd** [comment]
Godaddy is the best

**Comment by Logan7432** [comment]
@Jhair2015 @alktbihd So those sights can run servers like this one?

**Comment by Jhair2015** [comment]
mmmmm No, Hosting is to host [xD] your website, and VPS is to Run your [MultiOgar] Server

**Comment by Jhair2015** [comment]
@Logan7432 Try my domain .io :D http://wair.io/

**Comment by alktbihd** [comment]
@Jhair2015 can you help me with my client :) ? i need help on very small things xd

**Comment by Logan7432** [comment]
@Jhair2015 Wow! Is that your site?

**Comment by Logan7432** [comment]
@Jhair2015 Check mine out at WilsonSD12.ooguy.com. I kinda need help though, my client lags behind and dosnt fell smooth like yours.

**Comment by Jhair2015** [comment]
@alktbihd May be xD. @Logan7432 Yes is my game :) .io domain just for 32$ lol and free VPS and very very very very very fast xD

**Comment by alktbihd** [comment]
free vps? @Jhair2015

**Comment by Logan7432** [comment]
@Jhair2015 Thx for spamming me with ads :) lol

**Comment by Jhair2015** [comment]
If by some contacts (:

**Comment by Jhair2015** [comment]
@Logan7432 Thanks for the money may be xd? lol

**Comment by Logan7432** [comment]
@Jhair2015 What do u use for the ads?

**Comment by Jhair2015** [comment]
@Logan7432 Exoclick, But I'll be using sekindo in a few hours lol

**Comment by Logan7432** [comment]
@Jhair2015 If Possible Would you be able to help me make that minimap you use? its fine if not.

**Comment by Jhair2015** [comment]
@Logan7432 I do not have much time now

**Comment by Logan7432** [comment]
@Jhair2015 Thats fine.

**Comment by Logan7432** [comment]
@Jhair2015 Do you use this version of multi ogar for your site?

**Comment by Jhair2015** [comment]
Some features, I have modified many things that I do not remember if the one I have in my vps is from MegaByte or Tyler xD

**Comment by Logan7432** [comment]
@Jhair2015 Ok, one last question. What VPS do you use?

**Comment by Jhair2015** [comment]
AWS

**Comment by Tyler3D** [comment]
@Logan7432 I recommend buying a server. Port-forwarding and running both the game-servers and website. It is both cheaper and you have more control.

**Comment by Mr-BrockLee** [comment]
@Logan7432 or @Tyler3D Do u guys have modified version of Cigar?

**Comment by Logan7432** [comment]
@Jhair2015 Yes, But im going to be rewriting my entire cigar client to match newest protocol and make everything cleaner

**Comment by alktbihd** [comment]
@Jhair2015 can u help me on something on my client? :)

**Comment by Logan7432** [comment]
@Jhair2015 Also, How did you get the background of your game like a map? I would really like to implement this to mine. Help?

**Comment by TigOlBittes** [comment]
@Logan7432  whats ur website?

**Comment by Mr-BrockLee** [comment]
@Logan7432 Nice site xD
@Wair1o17 What client do you use?

**Comment by Logan7432** [comment]
@Mr-BrockLee Yeah, its pretty good for a site I made for school.

**Comment by AGarRiBiA** [comment]
http://k-d.io
lol
