### ISSUE TITLE
Lose mass according to the players

### ISSUE THREAD

**Issue by RelTakeover** [Tyler3D/Multi-Ogar-Edited-Unlimited#12]
This method is much better than all, the massdecay is updated according to players who enter the server, if there are more players the value will be higher, megabyte told me how to do it but for a very old version, how do I do it?

**Comment by Tyler3D** [comment]
Go to line 648 of gamserver.js

**Comment by Tyler3D** [comment]
change that line to 
var rate = this.config.playerDecayRate * .1 * this.clients.length;

**Comment by Tyler3D** [comment]
With 50 players you lose mass really fast

**Comment by Tyler3D** [comment]
Change the .1 to affect the decay rate @RelTakeover

**Comment by Tyler3D** [comment]
nvm its here
https://github.com/Tyler3D/Multi-Ogar-Edited-Unlimited/blob/master/src/GameServer.js#L632

**Comment by gyeyoqu** [comment]
The other method was more effective, can you help me? For each player added 0.00001 of decay
