### ISSUE TITLE
How to?

### ISSUE THREAD

**Issue by Wair1o17** [Tyler3D/Multi-Ogar-Edited-Unlimited#122]
How to add an image above the cell (this is not client sided), for example add a crown and appease with the same pellet system ...

Please help!

**Comment by imnotNxhz1** [comment]
hazle un chupon a los developers de laxuz y te diran como  :v    theoxt y pay2win xD

**Comment by Wair1o17** [comment]
Jajaja :v Ellos no saben :'v
