### ISSUE TITLE
skin

### ISSUE THREAD

**Issue by gyeyoqu** [Tyler3D/Multi-Ogar-Edited-Unlimited#16]
I want to allow a certain ip to only use a selected skin

Do not say that it is client-sided, because what corresponds to ip is completely backend.

**Comment by Tyler3D** [comment]
@Megabyte918 Already gave you the answer. Please don't make two duplicate issues on two repos. Either ask on mine or Mega's repo and wait for an answer. If you don't get one thennn, you can ask on the other one
