### ISSUE TITLE
playercommands

### ISSUE THREAD

**Issue by gyeyoqu** [Tyler3D/Multi-Ogar-Edited-Unlimited#17]
There are some commands that can only be given to yourself, can you make them give to others? Like mass or spawnmass

**Comment by Tyler3D** [comment]
All of the commands can be given to others. All you have to do is request their id/tell them to do /id. Then put the id after the command and first argument. Like /mass 500 1 change player id 1 to 500 mass. The only commands that are missing are kill and skin. But the problem with the kill command is that why would a player give you his id to kill him? You could also do kick. And the Skin command is useless to use on others

**Comment by Tyler3D** [comment]
@gyeyoqu

**Comment by gyeyoqu** [comment]
thanks
