### ISSUE TITLE
Gota.io physics config

### ISSUE THREAD

**Issue by gyeyoqu** [Tyler3D/Multi-Ogar-Edited-Unlimited#18]
Could you make spaces like gota.io? That game is really played, even if it is put in an option in gameserver.ini if ​​you want to activate it

**Comment by Tyler3D** [comment]
@gyeyoqu That would take hours of me playing both gota.io and the server in order to get similar physics. And I don't have the time

**Comment by Jhair2015** [comment]
@Tyler3D We could gather people to dominate a server, I would be in with pleasure xD, We join in the discord xDD

**Comment by gyeyoqu** [comment]
tyler3d , is hard do this?

**Comment by Tyler3D** [comment]
@gyeyoqu Yep, I managed to make Gota.io like instant-merge but, thats it

**Comment by gyeyoqu** [comment]
Oh and ffa mode? Will be cool😎

**Comment by Megabyte918** [comment]
@Tyler3D What are you planning to do with this? You mentioned in #65 that do not suggest physics configurations as they lag the game, and this has been open for almost a month. 
@gyeyoqu If you want to get splits like Gota.io, I suggest playing around with the `splitVelocity` config

**Comment by Tyler3D** [comment]
@Megabyte918 True actually I just forgot about this lol.
