### ISSUE TITLE
Superpowers Gamemode

### ISSUE THREAD

**Issue by gyeyoqu** [Tyler3D/Multi-Ogar-Edited-Unlimited#20]
A game mode called superpowers:

EVERY 1:00 - 1:30 MINUTE YOU CAN CHOOSE BETWEEN THESE POWERS

- That you can throw every 1:00 minute one virus instead of food. And that in a div on the screen tell how many seconds are left before you can re-launch viruses

Super speed for 10 seconds without losing mass, every 1:20 minutes and in a div on the screen tell how many seconds are left before you can set super speed.

Add me 1000 of mass every 1:00 minute , and in a div on the screen tell how many seconds are left before you can set mass.

Throw giant points for 20 seconds, every 1 minute and in a div on the screen tell how many seconds are left before you can set mass.

Add me 5 minions temporaly every 1:30 minutes and in a div on the screen tell how many seconds are left before you can set mass.

ENJOY

**Comment by Tyler3D** [comment]
I don't have much free time until next week because of school. So I will work on this soon. @gyeyoqu

**Comment by Tyler3D** [comment]
@gyeyoqu Done
