### ISSUE TITLE
sound and message

### ISSUE THREAD

**Issue by gyeyoqu** [Tyler3D/Multi-Ogar-Edited-Unlimited#22]
When between an administrator or a moderator, in the chat a message that says "A MODERATOR HAS JOIN" and has some sound

**Comment by Tyler3D** [comment]
@gyeyoqu The chat message I can do but the sound is impossible due to how the protocol is structured. And no, I can't change it.

**Comment by Tyler3D** [comment]
Actually this isn't a good idea because everybody would act differently if a admin or mod joined and their purpose is to ban and kick people that are aggressive and mean in chat.

**Comment by Logan7432** [comment]
@Tyler3D you could make this a plugin or a option to have on/off in the config. I personally like this idea
