### ISSUE TITLE
SC 

### ISSUE THREAD

**Issue by gyeyoqu** [Tyler3D/Multi-Ogar-Edited-Unlimited#25]
https://raw.githubusercontent.com/Agarian/OgarUL-Plugin-Library/master/SkinChanger/index.js

`I have been trying to adapt the LegitSoulja SkinChanger plugin for Multiogar, but I have not been able, can you do anything?`

**Comment by gyeyoqu** [comment]
you can give me your discord ? thanks =)

**Comment by LegitSoulja** [comment]
@gyeyoqu hey, however this specific script cannot be implemented into Multi-Ogar. You'll have to manually write your own code in which will do that to players.

However, I don't work on other Ogar platforms. I don't like the idea of having multiple projects with the same aspects. It get annoying, as of how minions was implemented into Multi-Ogar. However, I didn't create it, nor find it so I have no say.

It's up to the owner of the repo to add this into the project, however I will not do so.

**Comment by gyeyoqu** [comment]
Oh , thanks @LegitSoulja

**Comment by Tyler3D** [comment]
If @LegitSoulja does mind I try to add this. I wouldn't feel right about copying his code/idea without asking.

**Comment by LegitSoulja** [comment]
@Tyler3D didn't I say?

**Comment by LegitSoulja** [comment]
You can make it better. You don't have to copy my code. You forked this project, so you should know how to code right?

The way this plugin is coded won't be the same with Multi-Ogar. You'll have to write it a special way in order for it to work.

**Comment by Tyler3D** [comment]
This is client related. Apparently when you try to change skins will in-game your skin will not change until you respawn. OgarUL client is different tho and I'm not going to add something that will only work on one client because that's isolation

**Comment by LegitSoulja** [comment]
? Maybe you should learn how to update the skin packet. This is nothing client related. This is Multi-Ogar related. Basically, with limited of knowledge you say it's impossible, but not. OgarUnlimited basically has ALOT of functionalities, in which being able to change skins without respawning. Dynamic player update.

**Comment by Tyler3D** [comment]
Well to be fair I only tested on agar.io client because all other clients I know of don't support skins. Besides OgarUL. Maybe Miniclip prevented skin change in-game?

**Comment by Tyler3D** [comment]
And your right. I'm learning how to code so Perhaps I did something wrong

**Comment by LegitSoulja** [comment]
@Tyler3D I'm pretty sure it's possible with any client. Agar.io especially, or am I wrong. Since I don't play Agar.io, I can't determine that. I haven't really looked at Multi-Ogar code. I mean, bascially it's Ogar that's more efficient but it's not something that I care about. I barely even play what I'm contributing or rather so used to contribute to.

**Comment by LegitSoulja** [comment]
Check out UpdateNodes. The skin hint is there, with the player nodes, which should be accessible for the Player class, which the code can be placed in the game server

**Comment by LegitSoulja** [comment]
@Tyler3D sorry, I meant the PlayerTracker.

**Comment by Tyler3D** [comment]
@LegitSoulja Thanks, sorry for the late response lol
