### ISSUE TITLE
how to ?

### ISSUE THREAD

**Issue by gyeyoqu** [Tyler3D/Multi-Ogar-Edited-Unlimited#28]
how to create new userroles ?

**Comment by Tyler3D** [comment]
https://github.com/Tyler3D/Multi-Ogar-Edited-Unlimited/blob/master/src/enum/UserRoleEnum.js#L13
Do define("[insert role"], [level]) The higher the level the more power

**Comment by Tyler3D** [comment]
Then add them to userRoles.json

**Comment by Tyler3D** [comment]
@gyeyoqu

**Comment by gyeyoqu** [comment]
thanks !!

**Comment by gyeyoqu** [comment]
not working for chat message prefix
