### ISSUE TITLE
Add

### ISSUE THREAD

**Issue by RelTakeover** [Tyler3D/Multi-Ogar-Edited-Unlimited#3]
hello ,you can add powerups?? 

if you press "k" you can gain 300 of mass 
Only once per round or at least tell me how I can do it

if you press "n" you can gain speed per 10 seconds

**Comment by Tyler3D** [comment]
I'm trying to make a deip.io level up system. I'm working on the script but I get way too much homework :/

**Comment by PsycoYT** [comment]
Ok :)

**Comment by Tyler3D** [comment]
I tried working on it but it wouldn't be practical so, I'm scrapping the idea. Maybe I'll think of something that could work.
