### ISSUE TITLE
prefix

### ISSUE THREAD

**Issue by gyeyoqu** [Tyler3D/Multi-Ogar-Edited-Unlimited#30]
i use cigar protocol 6 and prefix for SERVER  IS

                var server = !!(flags & 0x80),

if i created rank "leyend" with:

`define("LEYEND", 5);`

what is this prefix?

**Comment by Tyler3D** [comment]
@gyeyoqu The prefix is client-sided however there is a solution.
Replace ChatMessage.js in the packet folder to: http://pastebin.com/MKEgM9mk
P.S. Creating a userrank isn't enough  you have to make commands only for leyend. You can see them in commandList.js. P.S. You miss spelled Legend xD. Tell me if works
