### ISSUE TITLE
Badwords

### ISSUE THREAD

**Issue by gyeyoqu** [Tyler3D/Multi-Ogar-Edited-Unlimited#32]
How can I do so that each rank can use certain forbidden names, even though they all have the same forbidden names in common

**Comment by Tyler3D** [comment]
https://github.com/Megabyte918/MultiOgar-Edited/issues/511 Wait until you get a response from that repo before you ask someone else @gyeyoqu

**Comment by gyeyoqu** [comment]
multiogar-Edited ,Has very bad helpers, you are better,And more humble please help me

**Comment by Tyler3D** [comment]
@gyeyoqu Just wait. @Megabyte918 Is nice too!

**Comment by Tyler3D** [comment]
Plus idk how to do this anyway. So I would need to figure it out

**Comment by gyeyoqu** [comment]
ok thanks TYLER3D
