### ISSUE TITLE
Can You add  youtuber rank please i really need it .

### ISSUE THREAD

**Issue by wayfarer2** [Tyler3D/Multi-Ogar-Edited-Unlimited#34]

**Comment by gyeyoqu** [comment]
like my agar , ogar.pw haha NO xd

**Comment by Tyler3D** [comment]
ogar.pw works by Changing the role in userRole.json "Moder" to "Youtuber" and then getting rid of the code for Moders in PlayerCommands.js @wayfarer2

**Comment by wayfarer2** [comment]
can you show me how to get rid of it please @Tyler3D

**Comment by Tyler3D** [comment]
@wayfarer2 https://github.com/Tyler3D/Multi-Ogar-Edited-Unlimited/blob/master/src/enum/userRoles.json#L11 Change MODER to YOUTUBER

**Comment by gyeyoqu** [comment]
and client changes @Tyler3D  @wayfarer2
