### ISSUE TITLE
servers crashes with last update

### ISSUE THREAD

**Issue by gyeyoqu** [Tyler3D/Multi-Ogar-Edited-Unlimited#37]
im using version 1.6.1 of lukas967

**Comment by Tyler3D** [comment]
@gyeyoqu What client?

**Comment by gyeyoqu** [comment]
protocol 6

**Comment by gyeyoqu** [comment]
PD : I love you

**Comment by Tyler3D** [comment]
What's the error?

**Comment by gyeyoqu** [comment]
wait

**Comment by gyeyoqu** [comment]
![image](https://cloud.githubusercontent.com/assets/25285427/22858412/18938bf4-f09b-11e6-8bc2-81e43e14a8bd.png)

**Comment by gyeyoqu** [comment]
getscore is not a function

**Comment by Tyler3D** [comment]
ohh I forgot Luka's version doesn't have the getScore function. Open UpdateLeaderboard.js and change all getScore() to ._score. Like this
var score = (this.leaderboard[i].getScore() / 100).toFixed(); becomes
var score = (this.leaderboard[i]._score / 100).toFixed();

**Comment by Tyler3D** [comment]
That should fix it @gyeyoqu

**Comment by gyeyoqu** [comment]
ok thanks i will try now

**Comment by gyeyoqu** [comment]
![image](https://cloud.githubusercontent.com/assets/25285427/22858482/b922d816-f09d-11e6-8430-9d0e85a7e9ec.png)

**Comment by Tyler3D** [comment]
Change all of the getFriendlyName's to _name

**Comment by gyeyoqu** [comment]
:(

**Comment by gyeyoqu** [comment]
![image](https://cloud.githubusercontent.com/assets/25285427/22858496/29df3504-f09e-11e6-87fa-d91dfb1f1e8c.png)

**Comment by gyeyoqu** [comment]
._name is not a function

**Comment by Tyler3D** [comment]
Change the ._name back to getFriendlyName

**Comment by Tyler3D** [comment]
PlayerTracker.prototype.getFriendlyName = function () {
    if (!this._name) this._name = "";
    this._name = this._name.trim();
    if (!this._name.length) 
        this._name = "An unnamed cell";
    return this._name;
};

**Comment by Tyler3D** [comment]
Add that to your playerTracker.js

**Comment by gyeyoqu** [comment]
what function i should replace ? setName?

**Comment by gyeyoqu** [comment]
tyler ?

**Comment by Tyler3D** [comment]
GetFriendlyName

**Comment by Tyler3D** [comment]
nvm don't replace just add it in playertracker

**Comment by gyeyoqu** [comment]
![image](https://cloud.githubusercontent.com/assets/25285427/22858596/dae58b26-f0a0-11e6-9dad-7d40dd4e581f.png)

**Comment by gyeyoqu** [comment]
see the LB

**Comment by gyeyoqu** [comment]
Why are you so humble?

**Comment by gyeyoqu** [comment]
Some programmers do not even respond, thank you =)

**Comment by gyeyoqu** [comment]
THE LB IS BUGGY

**Comment by gyeyoqu** [comment]
only show the first digit

**Comment by gyeyoqu** [comment]
oh , i fixed this. thanks !!!

**Comment by Tyler3D** [comment]
how did you fix it?

**Comment by Tyler3D** [comment]
Sorry for the late respond I had to go somewhere

**Comment by gyeyoqu** [comment]
only remove the division for 100 XD

**Comment by gyeyoqu** [comment]
thanks !!

**Comment by gyeyoqu** [comment]
tyler , you can help me with a thing? :c

**Comment by gyeyoqu** [comment]
actual update pos is so buggy

**Comment by gyeyoqu** [comment]
![image](https://cloud.githubusercontent.com/assets/25285427/22859085/b10465e8-f0af-11e6-914c-e048bf2f668b.png)

**Comment by gyeyoqu** [comment]
i will try fix XD

**Comment by gyeyoqu** [comment]
the current pos have much bugs

**Comment by Tyler3D** [comment]
It's not like that on protocol 6 Imma fix but I have to finish my homework

**Comment by gyeyoqu** [comment]
ok i will waiting here =)

**Comment by gyeyoqu** [comment]
hey?

**Comment by gyeyoqu** [comment]
hey ? i waiting =)

**Comment by gyeyoqu** [comment]
waiting :(

**Comment by gyeyoqu** [comment]
waiting XD

**Comment by Tyler3D** [comment]
@gyeyoqu Fixed

**Comment by gyeyoqu** [comment]
how use name in the current pos instead of text "position"

**Comment by Tyler3D** [comment]
@gyeyoqu It doesn't fit on leaderboard. I tried
