### ISSUE TITLE
Where can I change the Auto Restart Time ?

### ISSUE THREAD

**Issue by FlareYT** [Tyler3D/Multi-Ogar-Edited-Unlimited#38]
Question is UP

Greetins Flare !

**Comment by Tyler3D** [comment]
@FlareYT There isn't a auto-restart system

**Comment by FlareYT** [comment]
Would it be possible to add one ? 

Greetins :)

**Comment by Tyler3D** [comment]
var _temp = new Date();
              if (((this.time.getTime() + (this.config.serverRestartInterval * 3600000) - _temp.getTime()) / 1000) <= 1)
              process.exit(3);

**Comment by Tyler3D** [comment]
https://github.com/Tyler3D/Multi-Ogar-Edited-Unlimited/blob/master/src/GameServer.js#L43
Add  this.time = new Date();

**Comment by Tyler3D** [comment]
https://github.com/Tyler3D/Multi-Ogar-Edited-Unlimited/blob/master/src/GameServer.js#L564
Add this

	     var _temp = new Date();
              if (((this.time.getTime() + (this.config.serverRestartInterval * 3600000) - _temp.getTime()) / 1000) <= 1)
               process.exit(3);

**Comment by Tyler3D** [comment]
@FlareYT

**Comment by FlareYT** [comment]
@Tyler3D , Im trying it , Thanks tho ! :)

Greetings Flare !
