### ISSUE TITLE
What is it?

### ISSUE THREAD

**Issue by Jhair2015** [Tyler3D/Multi-Ogar-Edited-Unlimited#39]
What is the AutoRestart ?, I mean this "https://github.com/Tyler3D/Multi-Ogar-Edited-Unlimited/commits/master" was looking for and with nothing still accomplished D:

**Comment by Tyler3D** [comment]
https://github.com/Megabyte918/MultiOgar-Edited/pull/267
@Jhair2015

**Comment by Tyler3D** [comment]
I didn't add it because it isn't really useful

**Comment by Jhair2015** [comment]
Nooo, for me if you use it, in your branch of updates you added that function, could you give me the link to it?

**Comment by Tyler3D** [comment]
@Jhair2015 I deleted it xD

**Comment by Jhair2015** [comment]
xd D:
