### ISSUE TITLE
How to add a Tag like : [Owner] , and a Rainbow Leaderboard !

### ISSUE THREAD

**Issue by FlareYT** [Tyler3D/Multi-Ogar-Edited-Unlimited#41]
Soo,

Im looking for the GameServer.js Line where I can change/add a Tag ! :)
Otherwise does any1 knows the script for the Rainbow Color? -> http://6gem.pw

Greetings Flare ! :)

**Comment by Tyler3D** [comment]
@FlareYT I recommend you make a admin user and login in as it. Idk of any script for Rainbow Color

**Comment by Tyler3D** [comment]
Although you can connect via this client to the server. Open up the console and type in
setserver("ip:port")

**Comment by TheJustExper** [comment]
Hey flare ;)

**Comment by FlareYT** [comment]
@TheJustExper didn't want to copy it :) 
@Tyler3D , The Client is not a Problem :) I got my Own game !

Otherwise Thanks :+1:
