### ISSUE TITLE
Self feed Gamemode

### ISSUE THREAD

**Issue by gyeyoqu** [Tyler3D/Multi-Ogar-Edited-Unlimited#43]
title

**Comment by Tyler3D** [comment]
@gyeyoqu What do you mean?

**Comment by gyeyoqu** [comment]
I can feed myself and grow like this and when there is only 1 player, the server is restarted

**Comment by Jhair2015** [comment]
@gyeyoqu That is already possible, gameserver.ini and the autoresestar that has given @Tyler3D  .-.
