### ISSUE TITLE
Badge in the name for admins and mods 

### ISSUE THREAD

**Issue by gyeyoqu** [Tyler3D/Multi-Ogar-Edited-Unlimited#47]
![image](https://cloud.githubusercontent.com/assets/25285427/23478453/35c2c56a-fea0-11e6-9bd8-320950291992.png)

**Comment by Jhair2015** [comment]
duplicate from MultiOgar Edited.

**Comment by Tyler3D** [comment]
@Jhair2015 your right. I'm not going to close tho because this isn't really client sided... at least I think

**Comment by gyeyoqu** [comment]
Yes, it is possible to draw in on server, since you only need to make an 'if' with the admin and draw an image next to the name

**Comment by Tyler3D** [comment]
Drawing an image like that is client sided but, I have another idea. Ill do it when I get home.

**Comment by gyeyoqu** [comment]
ok , you want play with me ? in my servers ? :3rd_place_medal:

**Comment by Tyler3D** [comment]
@gyeyoqu Done

**Comment by gyeyoqu** [comment]
is impossible a image?

**Comment by Tyler3D** [comment]
@gyeyoqu Yup, a image is client-sided

**Comment by gyeyoqu** [comment]
The problem is that I do not understand how to make a "IF" on the client if the player is admin ...

**Comment by Tyler3D** [comment]
That's not the problem. The problem is that drawing an image is tricky.

**Comment by Tyler3D** [comment]
Plus the server doesn't tell the client if a player is admin either. It's only on chat

**Comment by gyeyoqu** [comment]
The chat messages have flag, as for example for the admin is 0x40, but what is the admin flag for the game itself?

**Comment by gyeyoqu** [comment]
Exact, then, what can I do?

**Comment by Tyler3D** [comment]
Edit both and make your own protocol. Which is a absolute pain, sadly

**Comment by gyeyoqu** [comment]
How could I make the server tell the client who is admin and who is not?

**Comment by Tyler3D** [comment]
Create a flag for admin in updateNodes.js and do the same client sided

**Comment by gyeyoqu** [comment]
My good friend tyler, help me create it :1st_place_medal:

**Comment by Tyler3D** [comment]
idk how to create custom protocols

**Comment by Tyler3D** [comment]
nvm, I mean idk how to make a website.

**Comment by gyeyoqu** [comment]
But the creation of a flag? work ?

**Comment by Tyler3D** [comment]
Change your UpdateNodes.prototype.writeUpdateItems6 in UpdateNodes.js with this
http://pastebin.com/i5A5f0QG

**Comment by Tyler3D** [comment]
Now you need your client to recognize flag 0x40 and make a image on that node/cell

**Comment by gyeyoqu** [comment]
i will try now ,im nervious

**Comment by Tyler3D** [comment]
And after that... I can't really help you.
Check out https://github.com/Luka967/Cigar/blob/master/www/assets/js/main_out.js#L1176 tho

**Comment by gyeyoqu** [comment]
i cant :( , anyone can use the ᴬᴰᴹᴵᴺ

**Comment by Tyler3D** [comment]
No only Amin's can

**Comment by Tyler3D** [comment]
Anyway gtg

**Comment by FlareYT** [comment]
@Tyler3D , what should be the Icons location and Name ? 

Greetings Flare
