### ISSUE TITLE
keep logged in for admins and mods

### ISSUE THREAD

**Issue by gyeyoqu** [Tyler3D/Multi-Ogar-Edited-Unlimited#48]
title

**Comment by Tyler3D** [comment]
`
    if (ws.remoteAddress == "*insert ip here") `{`
        ws.playerTracker.userRole = 4;
    }
`
Add that to the end of your onClientSocketOpen function in gameServer.js
For example:
`
    if (ws.remoteAddress == "127.0.0.1") `{`
        ws.playerTracker.userRole = 4;
    }
`
Gives localhost or ip 127.0.0.1 admin permissions
2 = Mod and 4 = Admin

**Comment by Tyler3D** [comment]
@gyeyoqu
