### ISSUE TITLE
Chat and accounts level

### ISSUE THREAD

**Issue by gyeyoqu** [Tyler3D/Multi-Ogar-Edited-Unlimited#49]
I like your updates, but what I do not like is that everything you do by chat, and what is that of accounts? it's finished?

**Comment by Tyler3D** [comment]
There really isn't much you can do beside chat and a few other things. Yes the account thing is finished
@gyeyoqu

**Comment by Tyler3D** [comment]
Now it is

**Comment by Tyler3D** [comment]
@gyeyoqu

**Comment by gyeyoqu** [comment]
you can add to the level system , skin per level ? and the level in the nick , or above of the nick? , is possible 
How could you make the client know the level of the player?

**Comment by gyeyoqu** [comment]
level in the nick or above of the nick , like agar MOBILE

**Comment by gyeyoqu** [comment]
i will implement your system bro

**Comment by gyeyoqu** [comment]
f you are high level, you start with more mass and you unlock the same skins of .io , possible?

**Comment by Tyler3D** [comment]
@gyeyoqu Nope The only thing that is possible is having your level next to your name which would look weird

**Comment by Tyler3D** [comment]
Whats your playerStartSize on your Servers?

**Comment by gyeyoqu** [comment]
and unlock skins?

**Comment by Tyler3D** [comment]
Thats impossible or at least to a degree

**Comment by Tyler3D** [comment]
You can stop people from putting <kraken> if they aren't level 100 but that would cause lag with a lot of people and would be living hell to code

**Comment by Tyler3D** [comment]
Can you give me admin on your servers. I'm bored xD

**Comment by gyeyoqu** [comment]
ok , so, for what i need the level system?

**Comment by Tyler3D** [comment]
What's your playerStartSize?

**Comment by gyeyoqu** [comment]
i dont undertand your ask

**Comment by Tyler3D** [comment]
the config playerStartSize

**Comment by gyeyoqu** [comment]
is possible lock the skins per level as badword?

**Comment by gyeyoqu** [comment]
and the level next to the name

**Comment by Tyler3D** [comment]
@gyeyoqu Sure, but they won't be good ideas

**Comment by Tyler3D** [comment]
Multi-Ogar-Edited-Unlimited is supposed to give you freedom to do whatever you want. Unlockable skins would be a bad idea

**Comment by Tyler3D** [comment]
And Levels next to your name in chat would work but not next to your name. It would look weird

**Comment by gyeyoqu** [comment]
Ok but you could add the blocking of the skins and if they want to disable it then in gameserver.ini, and the level next to the nick in the chat , will be good

**Comment by Tyler3D** [comment]
People won't want to play on your server if you block skins and sure

**Comment by gyeyoqu** [comment]
I know how to manage my server

**Comment by Tyler3D** [comment]
http://pastebin.com/L61FP1rn

**Comment by gyeyoqu** [comment]
what ? idk about javascript server side

**Comment by Tyler3D** [comment]
You have to do this -->
if (skinname == "kraken" && this.socket.playerTracker.level != 100) {
skinname = null
}
For each of the skins. Do it in the setName function in PacketHandler.js

**Comment by gyeyoqu** [comment]
1)If the account already exists, it is created anyway.
2)If you are logged in, your id is not displayed

**Comment by gyeyoqu** [comment]
![image](https://cloud.githubusercontent.com/assets/25285427/23589108/41972da0-01a6-11e7-8622-a7d49908a875.png)

Exp to level: NaN

**Comment by gyeyoqu** [comment]
```
 if (skinName == "fly" && this.socket.playerTracker.level > 5) {
skinName = null
}
```

THIS NOT WORK FOR ME :(

**Comment by Tyler3D** [comment]
Because its < not >

**Comment by gyeyoqu** [comment]
i put the skin with /skin fly

**Comment by gyeyoqu** [comment]
and show me the skin :(

**Comment by gyeyoqu** [comment]
with the command

**Comment by Tyler3D** [comment]
Remove the skin command then

**Comment by Tyler3D** [comment]
I fixed the Nan thing
