### ISSUE TITLE
sc BUG

### ISSUE THREAD

**Issue by gyeyoqu** [Tyler3D/Multi-Ogar-Edited-Unlimited#54]
![image](https://cloud.githubusercontent.com/assets/25285427/23590802/5e27cc4e-01c5-11e7-9c38-b2182a919478.png)

L O L

**Comment by Tyler3D** [comment]
@gyeyoqu That's supposed to happen. Every Cell has a different skin

**Comment by gyeyoqu** [comment]
not

**Comment by gyeyoqu** [comment]
It is supposed to change the skin, but the same skin in all cells

**Comment by gyeyoqu** [comment]
like OGARUL

**Comment by Tyler3D** [comment]
that would be really laggy

**Comment by gyeyoqu** [comment]
Because it would be more lagged ? :c
