### ISSUE TITLE
How do this

### ISSUE THREAD

**Issue by gyeyoqu** [Tyler3D/Multi-Ogar-Edited-Unlimited#56]
I have playermaxcells in 16 and the virus explosion in 22 cells,  how do for when i explode a virus the playerMaxCells change to 22 for 10 seconds , how? Thanks

**Comment by Tyler3D** [comment]
https://github.com/Tyler3D/Multi-Ogar-Edited-Unlimited/blob/master/src/entity/Virus.js#L34
Change this.gameServer.playerMaxCells to 20
