### ISSUE TITLE
Decayrate per player

### ISSUE THREAD

**Issue by gyeyoqu** [Tyler3D/Multi-Ogar-Edited-Unlimited#59]
hey 

> 
> and when one player join to the server the decayrate increase 0.0001
> 
> i think this code work for the decayrate
> 
> for (var i = 0; i < this.socketCount; i++) {
> rate += 0.0001;
> }
> 
> but , not work for me ( or At least I think so)

**Comment by Tyler3D** [comment]
https://github.com/Tyler3D/Multi-Ogar-Edited-Unlimited/issues/12
do .0001 instead of .1

**Comment by gyeyoqu** [comment]
thx

**Comment by gyeyoqu** [comment]
lol not work

**Comment by Tyler3D** [comment]
@gyeyoqu Because the line changed here https://github.com/Tyler3D/Multi-Ogar-Edited-Unlimited/blob/master/src/GameServer.js#L1106

**Comment by gyeyoqu** [comment]
error :c

**Comment by gyeyoqu** [comment]
```
GameServer.prototype.updateMassDecay = function() {
    if (!this.config.playerDecayRate) return;
    
    // Loop through all player cells
    for (var i = 0; i < this.clients.length; i++) {
        var client = this.clients[i].playerTracker;
        for (var j = 0; j < client.cells.length; j++) {
            var cell = client.cells[j];
            if (cell == null || cell.isRemoved) 
                continue;
            var size = cell._size;
            if (size <= this.config.playerMinSize)
                continue;
            var rate = this.config.playerDecayRate;
            var massCap = this.config.playerDecayCap;
            if (massCap && cell._mass > massCap) rate *= 10;
            for (var i = 0; i < this.socketCount; i++) {
rate += .0006;
}
            size = Math.sqrt(size * size * decay);
            size = Math.max(size, this.config.playerMinSize);
            if (size != cell._size) {
                cell.setSize(size);
            }
        }
    }
};
```

**Comment by gyeyoqu** [comment]
correct?

**Comment by Tyler3D** [comment]
no

**Comment by Tyler3D** [comment]
@gyeyoqu Because the line changed here https://github.com/Tyler3D/Multi-Ogar-Edited-Unlimited/blob/master/src/GameServer.js#L1106

**Comment by gyeyoqu** [comment]
He changed the line you say for the code, which I do wrong ^?

**Comment by Tyler3D** [comment]
`GameServer.prototype.updateMassDecay = function() {
    if (!this.config.playerDecayRate) return;
    
    // Loop through all player cells
    for (var i = 0; i < this.clients.length; i++) {
        var client = this.clients[i].playerTracker;
        for (var j = 0; j < client.cells.length; j++) {
            var cell = client.cells[j];
            if (cell == null || cell.isRemoved) 
                continue;
            var size = cell._size;
            if (size <= this.config.playerMinSize)
                continue;
            var rate =  this.config.playerDecayRate * .1 * this.clients.length;
            var massCap = this.config.playerDecayCap;
            if (massCap && cell._mass > massCap) rate *= 10;
            var decay = 1 - rate * this.gameMode.decayMod;
            size = Math.sqrt(size * size * decay);
            size = Math.max(size, this.config.playerMinSize);
            if (size != cell._size) {
                cell.setSize(size);
            }
        }
    }
};`

**Comment by gyeyoqu** [comment]
That way how much will be added by each player?

**Comment by gyeyoqu** [comment]
.1 per player ? is not too much ?

**Comment by Tyler3D** [comment]
0.0001

**Comment by gyeyoqu** [comment]
if i changed the ".1" for ".0006" the decayrate will loss 0.0006?

**Comment by Tyler3D** [comment]
Yea
