### ISSUE TITLE
Nice =)

### ISSUE THREAD

**Issue by RelTakeover** [Tyler3D/Multi-Ogar-Edited-Unlimited#6]
Hello i love your work.

You can add some of these characteristics:

1 - server sided minimap.
2 - anti teams mode
3 - bots per ip
4 - SkinChanger (I would love this)

**Comment by Tyler3D** [comment]
@RelTakeover 
1. What do you mean?
2. Sure.
3. not really useful because you can use commands to get bots
4. idk how I would make one

**Comment by Tyler3D** [comment]
Ill work on anti-team tho

**Comment by RelTakeover** [comment]
thanks , i mean a minimap like alis.io is really good =)

**Comment by Tyler3D** [comment]
@RelTakeover I tried making anti-team and did but got extreme lag. I'm talking lag by yourself lag. So, im not going to do anti- team. minimaps are already in multi-ogar you just need to find a client that has one.

**Comment by Jhair2015** [comment]
@RelTakeover That is socket

**Comment by Logan7432** [comment]
@Tyler3D Do you know of any clients that have working mini map with multi ogar? My client mini map is way way off with multi ogar
