### ISSUE TITLE
Self feed gamemode

### ISSUE THREAD

**Issue by gyeyoqu** [Tyler3D/Multi-Ogar-Edited-Unlimited#62]
I tried to do the self feed gamemode,  only change the ejecmassloss, but is so laggy , you can do without lag?

**Comment by FlareYT** [comment]
Well...

If it's lagging , it your Computer/VPS.
Im also running a Selffeed Mode ( http://ogario.gq) and its running clearly without Laggs.
Otherwise its running on a VPS.

Greetings Flare.

**Comment by Tyler3D** [comment]
^^^^
But, to reduce lag... https://github.com/Tyler3D/Multi-Ogar-Edited-Unlimited/blob/master/src/GameServer.js#L1553
Change this to 
var ejected = new Entity.Food(this, null, pos, this.config.ejectSize);

**Comment by Tyler3D** [comment]
@gyeyoqu
