### ISSUE TITLE
Login System

### ISSUE THREAD

**Issue by FlareYT** [Tyler3D/Multi-Ogar-Edited-Unlimited#63]
Well,

I know that it's not only Multi-Ogar "Sided" , but I still wanted to ask , if any1 wants to help me with a Level System.
I only want these Features : 
-Level Up = More Mass / Minions (+1 Level = 1 more Minion)
-Login System
------------------------------------------------------------------
Thats it :)

Greetings Flare

Ps : http://ogario.gq , where it should get added.
Pss : I got a Windows VPS , so it wouldn't be a problem with the MySQL things.

**Comment by Tyler3D** [comment]
@FlareYT I already did this. Do /account in the chat to get more info.
But this only gives you extra mass
For minions:
At the bottom of your login function in PlayerCommand.js
before the return add --> 
        this.playerTracker.minionControl = true;
        for (var i = 0; i < user.level; i++) {
            this.gameServer.bots.addMinion(this.playerTracker);
        }

**Comment by FlareYT** [comment]
@Tyler3D thanks for showing me , didn't updated it yet :+1: 

Greetings Flare

**Comment by FlareYT** [comment]
Well , 

I just updated my Version , everything works fine beside the Skins.
It can't be my Client , because it worked b4.
You could take a Look : http://ogario.gq - All Servers are using Multi-Ogar 1.4.8 (Your Version) where the Skins are working.
In the Developer Server (Updated one) the skins aren't working.

Greetings Flare

Ps : Im going to try it with Cigar in a Sec.
