### ISSUE TITLE
Tags / Minion Name

### ISSUE THREAD

**Issue by FlareYT** [Tyler3D/Multi-Ogar-Edited-Unlimited#64]
Hello,

Would it be possible to add a Tag like [Admin] , when a Admin logins.
I already have a Code , but I don't really know where to put it.
Example : http://mgar.io
Otherwise does any1 know how to name the Bots like the Usersname : 
If my Name is "Flare" , the Bots name should be "Flares Bot" .
I already tried to use : this.name + "Bot" , which didn't work that good.

Greetings Flare :)

**Comment by Tyler3D** [comment]
@FlareYT 
 if (user.Role = UserRoleEnum.ADMIN) var text = "The Admin" + "[" + name + "]" + " has joined in the game!
    for (var i in this.gameServer.clients) {
        var client = this.gameServer.clients[i].playerTracker;
        this.gameServer.sendChatMessage(null, client, text);
    }
^
Use that in your login function towards the bottom but before the return;
Find --> this.gameServer.bots.addMinion(player);
Change it to this.gameServer.bots.addMinion(player, (player._name + " Bot"));
Also Find --> this.gameServer.bots.addMinion(client);
And change it to this.gameServer.bots.addMinion(client, (client._name + " Bot"));

**Comment by gyeyoqu** [comment]
Tyler it nor work for me
