### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by Tyler3D** [Tyler3D/Multi-Ogar-Edited-Unlimited#66]
Any Questions you would like to ask. :)
I will only help if you show your attempt so, I can then help you.

**Comment by Agario2000** [comment]
Where do I download the plugins?

**Comment by Tyler3D** [comment]
@Agario2000 I've not made any yet

**Comment by Agario2000** [comment]
So there is a folder called "plugins"?

**Comment by FlareYT** [comment]
@Tyler3D , could you make a Plugin Template , so I know how they need to be coded.

Greetings Flare

**Comment by Tyler3D** [comment]
I will when I get home. I just didn't have time to make any plugins yesterday.

**Comment by Tyler3D** [comment]
@FlareYT @Agario2000 https://github.com/Tyler3D/Multi-Ogar-Edited-Unlimited-Plugins

**Comment by FlareYT** [comment]
@Tyler3D , how can I add something like players get +1 Minion every 5 Level ?
When its every 1 Level , its too much.

Greetings Flare.

**Comment by Tyler3D** [comment]
@FlareYT 
for (var i = 0; i < user.level; i++) {
this.gameServer.bots.addMinion(this.playerTracker);
}
Remember this... change it to 
for (var i = 0; i < ~~(user.level / 5); i++) {
this.gameServer.bots.addMinion(this.playerTracker);
}

**Comment by FlareYT** [comment]
@Tyler3D , Thank you so much 😆 
Otherwise would you like to join my Team of my Game ? I would take care of the Client (PHP,Html,CSS) and you could help me with the Servers (JS , im not that good in it)

Greetings Flare

**Comment by Agario2000** [comment]
How to change the auto restart time?

**Comment by Tyler3D** [comment]
@Agario2000 Change the restartInterval variable in the autorestart plugin

**Comment by Agario2000** [comment]
And how can I remove the "restarting" message from the leaderboard?

**Comment by gyeyoqu** [comment]
the client can know what is the level of the players?

**Comment by Tyler3D** [comment]
@Agario2000 Get rid of these lines
        this.PluginHandler.plugins.AutoRestart.timeleft = ((this.PluginHandler.plugins.AutoRestart.time + (this.PluginHandler.plugins.AutoRestart.restartInterval) - _time.getTime()) / 1000);
        this.leaderboard.splice(this.config.serverMaxLB - 1, 1, (this.PluginHandler.plugins.AutoRestart.fake_player));
        this.PluginHandler.plugins.AutoRestart.updateTick();

**Comment by Tyler3D** [comment]
@gyeyoqu That would require protocol modifications and would cause lag.

**Comment by Agario2000** [comment]
Can you set it to auto restart when you reach a specified mass amount?

**Comment by Jhair2015** [comment]
How to config it

`this.PluginHandler.plugins.AutoRestart.timeleft = ((this.PluginHandler.plugins.AutoRestart.time + (this.PluginHandler.plugins.AutoRestart.restartInterval) - _time.getTime ()) / 1000) ; 
this.leaderboard.splice (this.config.serverMaxLB - 1, 1, (this.PluginHandler.plugins.AutoRestart.fake_player)); 
this.PluginHandler.plugins.AutoRestart.updateTick ();`

For when a few seconds are missing, a message in LeaderBoard or AutoRestart in a few Seconds!

**Comment by Logan7432** [comment]
Hey, Just a question. Would anyone here by any chance know how to code the mini-map for the client side? Because for some odd reason multi ogar dosnt work with my client minimap. https://ibb.co/gou9dv

**Comment by Logan7432** [comment]
Also, When do you think there will be a fix for the feeding/Ejecting mass?

**Comment by Logan7432** [comment]
@Tyler3D I know your very busy, but if you ever game time could you please help me fix my mini map for my client? I run the server for my school and it's very hard to find friends without a working mini map and you would be a huge help.
