### ISSUE TITLE
Skins aren't working anymore.

### ISSUE THREAD

**Issue by FlareYT** [Tyler3D/Multi-Ogar-Edited-Unlimited#69]
I just updated my Version to the newst one and now the Skins aren't working.
http://ogario.gq
All Servers , beside Developer Server , are running on Tylers MultiOgar Edit 1.4.8 , where the skins are working well.
On the Developer Server (Newest One) , the skins aren't showing.
Maybe someone knows how to fix it.

Greetings Flare

Ps : @Tyler3D maybe you could join my Discord or add me on Skype : https://discord.gg/NNfrmcc ; SeemsLikeFlare

**Comment by Tyler3D** [comment]
@FlareYT https://github.com/Tyler3D/Multi-Ogar-Edited-Unlimited/commit/d8886a39e487e1eea4fa4d21fbba289e8247e7e6 Try reverting this commit. Or you can update your client to the latest verison of Cigar

**Comment by FlareYT** [comment]
@Tyler3D , still not working.
Otherwise I downloaded the newest Version , with the new Plugins.
Well thats the error which I got : === Started 2017-03-09T21-01-41-702 ===
[INFO ][21:01:41] 0 IP ban records loaded.
[INFO ][21:01:41] 3 user records loaded.
[INFO ][21:01:41] 419 bad words loaded
[INFO ][21:01:41] [1m[32mMultiOgar-Edited-Unlimited 1.0.3[37m - An open source multi-protocol ogar server[0m
[FATAL][21:01:41] C:\Users\Administrator\Desktop\new servers\Multi-Ogar-Edited-Unlimited-master\src\plugins\Readme.md:1
(function (exports, require, module, __filename, __dirname) { This is where you store your plugins!
                                                                   ^^
SyntaxError: Unexpected identifier
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at PluginHandler.start (C:\Users\Administrator\Desktop\new servers\Multi-Ogar-Edited-Unlimited-master\src\PluginHandler.js:41:19)
    at PluginHandler.load (C:\Users\Administrator\Desktop\new servers\Multi-Ogar-Edited-Unlimited-master\src\PluginHandler.js:33:7)
[WARN ][21:01:41] RESTARTING SERVER


Greetings Flare.

**Comment by Tyler3D** [comment]
@FlareYT delete the readme from the plugins folder. I'll fix when I get home

**Comment by FlareYT** [comment]
@Tyler3D , well... I still didn't got the Skins fixxed , which means I can't use it :/
Maybe you would like to help me , I would appreciate it.
But thanks for trying to help me :+1: 

Greetings Flare

Ps: Keep the Great Work :)
