### ISSUE TITLE
2 hours trying 

### ISSUE THREAD

**Issue by gyeyoqu** [Tyler3D/Multi-Ogar-Edited-Unlimited#71]
I have a big problem , when i put your level system in Multiogar of megabyte i have this error

![image](https://cloud.githubusercontent.com/assets/25285427/23728098/cc3d8edc-0439-11e7-9fd1-ec68abbf90b3.png)

**Comment by Tyler3D** [comment]
@gyeyoqu Stop making issues about other repos. Or you may end up with a ban. Read the issue template

**Comment by gyeyoqu** [comment]
oh , but you can help me with this , please?

**Comment by gyeyoqu** [comment]
please man..

**Comment by gyeyoqu** [comment]
i need this tyler , please

**Comment by Jhair2015** [comment]
duplicate and more duplicate

**Comment by gyeyoqu** [comment]
sh jhair your server sucks

**Comment by Jhair2015** [comment]
i dont have server
