### ISSUE TITLE
How to do this?

### ISSUE THREAD

**Issue by Jhair2015** [Tyler3D/Multi-Ogar-Edited-Unlimited#73]
As I can make possible less lag, I mean to remove all unnecessary having to do with vanilla protocol (11) in order to have a better performance :)
 charcoal VPS powerful :(

**Comment by Tyler3D** [comment]
@Jhair2015 Multi-Ogar-Edited-Unlimited has a similar performance to Multi-Ogar-Edited. Most of the lag comes from gamemode stuff and unless you use those gamemodes you shouldn't lag
