### ISSUE TITLE
Power per level

### ISSUE THREAD

**Issue by gyeyoqu** [Tyler3D/Multi-Ogar-Edited-Unlimited#75]
For each level that increases, the player can choose a power between 'rec mode' 1k of mass' 'speed', all this for a round until he dies

And in the chat will say:

- you have raised a level, you can choose 'R', 'M', 'S'

And the player must write in chat /power R

If he want REC

R = REC
M = MASS
S = SPEED

All for one round, until he dies and regains level

**Comment by Tyler3D** [comment]
Seems like a lot of performance issues.
