### ISSUE TITLE
How to Change Mass of the Bots (Console Command)

### ISSUE THREAD

**Issue by FlareYT** [Tyler3D/Multi-Ogar-Edited-Unlimited#76]
Hey Guys,

I wanted to ask if somebody knows how I have to modify the minion Command , so I can give them Mass in through the Console Command .
Example : minion {ID} {Amount} ->{Mass}<- {Name}

Greetings Flare :)

**Comment by Tyler3D** [comment]
First, I have to ask @Andrews54757 Permission to port his "SuperMinions" plugin to this fork

**Comment by Andrews54757** [comment]
@Tyler3D You can do it. I dont care. OgarUL is over and therefore its code can be used by anyone.

**Comment by Tyler3D** [comment]
@FlareYT Done

**Comment by Jhair2015** [comment]
We miss OgarUL
