### ISSUE TITLE
Communication Optionally

### ISSUE THREAD

**Issue by gyeyoqu** [Tyler3D/Multi-Ogar-Edited-Unlimited#77]
Your fork consists in "UNLIMITED"

you can make that the client can know what is the level of players and all updates?

It would be great and so you could communicate in every aspect the client with the server

That the server know the level of players and obviusly add a configurable ( clientLevel = 0)
That the server know who is top 1 , top 2 , etc ( clientLB = 0 )
That the server know the own position ( clientOwn = 0 )
That the server know if is Slither Mode (clientSlither = 0)

This will be the better characteristic, since nobody focuses on the communication between client and server

Please do not close this suggestion

**Comment by Tyler3D** [comment]
@gyeyoqu That would require protocol changes which would make this server incompatible with all other clients.
