### ISSUE TITLE
How to changue it?

### ISSUE THREAD

**Issue by Jhair2015** [Tyler3D/Multi-Ogar-Edited-Unlimited#78]
#How to changue Plugins to MultiOgarEditedUnlimited

How can I make AutoRestart appear when only one minute or less is missing, also change the leaderboard mass + position; Just leave one such as mass and position to leave it aside, How is that possible :)

**Comment by Tyler3D** [comment]
https://github.com/Tyler3D/Multi-Ogar-Edited-Unlimited-Plugins/blob/master/AutoRestart.js#L33
That 5 is in seconds
The mass + position is separate would require recoding the entire plugin. And I'm too lazy lol. But you can take a look at how the functions looked when they were configurable
https://github.com/Tyler3D/Multi-Ogar-Edited-Unlimited/commit/866ace3b9e59bb5af2c4550ed789c9722530a817

**Comment by Tyler3D** [comment]
@Jhair2015

**Comment by Jhair2015** [comment]
lol thanks tyler again :)
