### ISSUE TITLE
old days

### ISSUE THREAD

**Issue by t11tanYT** [Tyler3D/Multi-Ogar-Edited-Unlimited#79]
are you remember old days in april 2016?
moneyclip patched bots in 5 may 2016
im want to back old days in private server like april 2016
ogar-feeder-bot-minions
ofbm (minions count) (name) (every how much ms bots will search your mouse coordinates and go to your mouse x y pos?) 
please  add it for this project (megabyte 918 closed this issue in his project )

**Comment by Tyler3D** [comment]
@t11tanYT I don't think this is too useful
