### ISSUE TITLE
Last man standing

### ISSUE THREAD

**Issue by gyeyoqu** [Tyler3D/Multi-Ogar-Edited-Unlimited#8]
In multi-edited lms starts when the lms command is placed, 
How do I start when there are 50 players and have at least 20 minutes to play?

**Comment by Tyler3D** [comment]
You have to code a timer

**Comment by gyeyoqu** [comment]
please help me :(

**Comment by Tyler3D** [comment]
https://github.com/Megabyte918/MultiOgar-Edited/tree/375b765bcdf59ca85d045ec27765c82422dc4af3

**Comment by Tyler3D** [comment]
@gyeyoqu That is Last Man Standing with a configurable timer
