### ISSUE TITLE
New gamemode

### ISSUE THREAD

**Issue by gyeyoqu** [Tyler3D/Multi-Ogar-Edited-Unlimited#81]
https://www.youtube.com/watch?v=41uCr7P28Ls

Gamemode like this video in the minute 3:14

**Comment by Jhair2015** [comment]
GameMode created by Theo

**Comment by gyeyoqu** [comment]
Who asked you?

**Comment by Tyler3D** [comment]
@gyeyoqu Please consider putting your suggestions in the suggestion issue. This is invalid

**Comment by Jhair2015** [comment]
@gyeyoqu Please be polite, as we to you.

**Comment by Megabyte918** [comment]
@Tyler3D Close?
