### ISSUE TITLE
Autorestart stops the server and not start it?

### ISSUE THREAD

**Issue by alktbihd** [Tyler3D/Multi-Ogar-Edited-Unlimited#82]
> [INFO ] 3 user records loaded.
> [INFO ] 419 bad words loaded
> [INFO ] MultiOgar-Edited-Unlimited 1.0.3 - An open source multi-protocol ogar server
> [PLUGINHANDLER] 2 Plugins loaded!
> [PLUGINHANDLER] AutoRestart 1.0.1 By Tyler3D Has been loaded!
> [INFO ] WebSocket: ws
> [INFO ] Started stats server on port 88
> [INFO ] Listening on port 443
> [INFO ] Current game mode is Free For All
> [AutoRestart] Restart in 0:0:59 Hours
> >[AutoRestart] RESTARTING!
> root@3rb:~/Self-Feed/src#

**Comment by Jhair2015** [comment]
use a script to 24/7 Server

**Comment by alktbihd** [comment]
Well, I want it to restart every 3 mins, is that possible?

**Comment by Jhair2015** [comment]
yes, just instal pm2 and run!

**Comment by alktbihd** [comment]
yeah but how do i configure it? ;-;


2017-03-21 19:22 GMT+04:00 JhairTera177 <notifications@github.com>:

**Comment by Tyler3D** [comment]
@alktbihd Run the script in the run folder which allows the server to restart.

**Comment by alktbihd** [comment]
oh

2017-03-22 0:18 GMT+04:00 Tyler3D <notifications@github.com>:
