### ISSUE TITLE
/login 

### ISSUE THREAD

**Issue by alktbihd** [Tyler3D/Multi-Ogar-Edited-Unlimited#83]
whenever i login i get login failed for some reason?.

**Comment by gyeyoqu** [comment]
@alktbihd show me your list of users and your PlayerCommand.js and the command that you are using

**Comment by Tyler3D** [comment]
@alktbihd Please update your issue to the issue template's example. I can't really help you if you don't give many details

**Comment by Logan7432** [comment]
Same problem... Typing everything in correctly

**Comment by Tyler3D** [comment]
Really?

**Comment by Logan7432** [comment]
@Tyler3D Yea Ill send you a few pics of my stuff, its all set up correctly

**Comment by Logan7432** [comment]
http://imgur.com/wgKelUa http://imgur.com/c0B0oTo

**Comment by Logan7432** [comment]
Also, make it a command so you a admin can do /id (player) so if we need to kick someone we know there id

**Comment by Logan7432** [comment]
This is weird because i create an account and right after I try to log in and it dosnt work says Login Failed

**Comment by Logan7432** [comment]
It would also be really cool if you like turn off chat but only admins and mods are allowed to chat.

**Comment by Logan7432** [comment]
Whats the pointof having the role admin but you cant use any commands to kick etc

**Comment by Logan7432** [comment]
Is it possible to do /playerlist in game as an admin like you can in console. Cause if im not at console and im somewhere else it would be nice to be able to find a player id from in game and kick someone.

**Comment by Tyler3D** [comment]
@Logan7432 Make sure you have the latest verision and do
/login Brigle Oreoham1

**Comment by Tyler3D** [comment]
The login system works perfectly for me

**Comment by Logan7432** [comment]
@Tyler3D works now! Thanks. Just need to fix the eject bug and were good.

**Comment by Logan7432** [comment]
@Tyler3D Can you make it so admins can do /kickbot? Also where do I got to change the amount of mass admins spawn in with?
