### ISSUE TITLE
Server Message

### ISSUE THREAD

**Issue by Logan7432** [Tyler3D/Multi-Ogar-Edited-Unlimited#84]
Is there a way to remove the message when you go into the game where it says Multi-Ogar unlimited (version number)

**Comment by Tyler3D** [comment]
@Logan7432 That message serves as a semi-copyright. If I tell you have to remove it then, you are basically stealing the server. If you know enough javascript you should be able to find it but, just remember that you are taking credit for mine and the original author's hard work.

**Comment by Logan7432** [comment]
@Tyler3D No No No, Im not trying to take credit at all. I just dont want my users to be seeing that every time they log in.
