### ISSUE TITLE
Login System Suggestion

### ISSUE THREAD

**Issue by Logan7432** [Tyler3D/Multi-Ogar-Edited-Unlimited#85]
So since theirs a leveling up system in the login system I think it would be an easy and awesome idea to have the server announce in the chat when someone levels up. Just a neat and cool feature that would be cool to have.

**Comment by Tyler3D** [comment]
Seems like this would cause a lot of spam @Logan7432

**Comment by Tyler3D** [comment]
And please in the future make your suggestion in the suggestions issue. Instead of making a separate one

**Comment by Logan7432** [comment]
@Tyler3D It would, but you would have the option to have it on or off, Of course I would like this feature.
