### ISSUE TITLE
SuperPowers

### ISSUE THREAD

**Issue by Logan7432** [Tyler3D/Multi-Ogar-Edited-Unlimited#88]
Theres a glitch with super powers for example if a bot or another player gets a power up, it says it in chat that they got the power up in my chat also making me think I got the power up but i really didnt.

**Comment by Logan7432** [comment]
And since you fixed the admin system when you create an account it dosnt say you registered anymore.

**Comment by Logan7432** [comment]
And apperently it lets you shoot mass or viruses in the mode only if you are really big and not split

**Comment by Logan7432** [comment]
Is there a way to remove the pop-split and the shooting virus from the super heroes game mode?

**Comment by Tyler3D** [comment]
Fixed

**Comment by Tyler3D** [comment]
Just remove the popsplit and shooting virus code from PowerUP.js

**Comment by Logan7432** [comment]
Thx

**Comment by Logan7432** [comment]
When Ever I delete the code I get an error.

**Comment by Logan7432** [comment]
Which line of code would I delete the remove shooting viruses and pop split
