### ISSUE TITLE
login 

### ISSUE THREAD

**Issue by vincent95330** [Tyler3D/Multi-Ogar-Edited-Unlimited#91]
I have problem with /login ( When i try to log in it crash )
http://ogarz.ovh/game/ (Selfeed 2 )

**Comment by Logan7432** [comment]
@vincent95330 Make Sure you have the most up to date server. Just a question, May I have the code for the minimap for the client? Cause for some reason my mini map dosnt work with this server and I notice that your mini-map works fine with the server. Can you please help me out?

**Comment by Logan7432** [comment]
Also just see for yourself on what im talking about. WilsonSD12.ooguy.com. Like my minimap is way off.

**Comment by Tyler3D** [comment]
^^
