### ISSUE TITLE
PowerUp

### ISSUE THREAD

**Issue by Logan7432** [Tyler3D/Multi-Ogar-Edited-Unlimited#92]
So I removed the line of code for the popsplit and shooting a virus. Which I wanted to do. But the power ups still spawn for the virus and popsplit but they dont give you any power up and just feed you.

**Comment by Tyler3D** [comment]
@Logan7432 Because you forgot to make this.power only give numbers between 1 and 2.

**Comment by Logan7432** [comment]
var Cell = require('./Cell');
var PlayerCell = require('./PlayerCell');
function PowerUP(gameServer) {
    Cell.apply(this, Array.prototype.slice.call(arguments));
    this.cellType = 2;
    this.isSpiked = false;
    this.isMotherCell = false; // Not to confuse bots
    this.setColor({ r: 0xff, g: 0x00, b: 0x94 });
    this.setSize(80);
    this.powertimer = 20 * 1000 // 20 Seconds
    this.power = Math.round(Math.random() * (4 - 1) + 1); // 1 = Speed 2 = Minions 3 = Virus shoot for 5 seconds 4 = One Popsplit Virus w shot
    this.gameServer = gameServer;
}
module.exports = PowerUP;
PowerUP.prototype = new Cell();

// Main Functions

PowerUP.prototype.onEaten = function (c) {
    var player = c.owner;
    var self = this;
    if (this.power == 1) {
        player.doublespeed = true;
            // OverRide
        this.gameServer.sendChatMessage(null, player, "You have been gived with Double Speed For 20 Seconds!");
        setTimeout(function() {
        player.doublespeed = false;
        self.gameServer.sendChatMessage(null, player, "Double Speed Eneded.");
        }, this.powertimer);
    } else if (this.power == 2) {
        player.minionControl = true;
        for (var i = 0; i < 5; i++) {
            this.gameServer.bots.addMinion(player);
        }
        this.gameServer.sendChatMessage(null, player, "You Have been Given Minions.");

        setTimeout(function() {
            player.minionControl = false;
            player.miQ = 0;
            self.gameServer.sendChatMessage(null, player, "You No Longer Have Minions.");
        }, this.powertimer);
    }
};

**Comment by Logan7432** [comment]
What do you mean?

**Comment by Tyler3D** [comment]
@Logan7432 this.power generates random numbers between 1 and 4. There are only choices for 1 and 2. Thus, there is 50% chance nothing will happen.

**Comment by Logan7432** [comment]
@Tyler3D Wheres the line of code to change it to 1 & 2? Also how do i make it so they power ups spawn a little less

**Comment by Tyler3D** [comment]
this.power = Math.round(Math.random() * (4 - 1) + 1);

**Comment by Tyler3D** [comment]
https://github.com/Tyler3D/Multi-Ogar-Edited-Unlimited/blob/master/src/gamemodes/SuperPowers.js#L13

**Comment by Logan7432** [comment]
@Tyler3D Thanks!

**Comment by Logan7432** [comment]
@Tyler3D I know this isnt related but do you know how to fix my clients mini-map? http://wilsonagario.x10host.com/
