### ISSUE TITLE
feeding

### ISSUE THREAD

**Issue by Logan7432** [Tyler3D/Multi-Ogar-Edited-Unlimited#93]
when is feeding planned to be fixed?

**Comment by Tyler3D** [comment]
@Logan7432 How impatient can you be to pressure someone to do something for you on a program that is already free.

**Comment by Logan7432** [comment]
@Tyler3D No No No, I'm not pressuring. What I meant was like will it be fixed sometime in the next few weeks? I Didn't mean it like that. its just a key thing in the game.
