### ISSUE TITLE
Problems with proxy minion ..

### ISSUE THREAD

**Issue by vincent95330** [Tyler3D/Multi-Ogar-Edited-Unlimited#94]
How can I forbid people to put their own minions with the tampermonkey extension in this multiogar? Like this project: https://github.com/Megabyte918/MultiOgar-Edited

**Comment by Logan7432** [comment]
@vincent95330 You cant at the minute unless this is updated to the most updated version of multiogar edited.

**Comment by Logan7432** [comment]
@vincent95330 Please check what I asked you in issue #93 Thanks

**Comment by Megabyte918** [comment]
This should be fixed now with the recently updated GameServer.js and it's minion detection. 
@Tyler3D close?

**Comment by Tyler3D** [comment]
^^
