### ISSUE TITLE
How to make popsplit work everytime?

### ISSUE THREAD

**Issue by SambyAgarYT** [Tyler3D/Multi-Ogar-Edited-Unlimited#96]

**Comment by Jhair2015** [comment]
@Megabyte918 How to tweak the virus explosion multipliers in Virus.js? Can you give me some clue to do it please!

**Comment by Tyler3D** [comment]
@Jhair2015 See the Multi-Ogar-Edited Wiki https://github.com/Megabyte918/MultiOgar-Edited/wiki/Frequently-Asked-Questions

**Comment by Tyler3D** [comment]
@SambyAgarYT But you should be able to use the popsplit command to give yourself perfect popsplits

**Comment by Jhair2015** [comment]
@Tyler3D Thanks :D again <3
