### ISSUE TITLE
Error's plugins!!!

### ISSUE THREAD

**Issue by ToporBigBots** [Tyler3D/Multi-Ogar-Edited-Unlimited#97]
Installed the plugin, turned on the server and the error appeared. There are only restart and template

**Comment by Logan7432** [comment]
Same issue!

**Comment by Logan7432** [comment]
@Tyler3D What happened?!

**Comment by Megabyte918** [comment]
Uninstall the plugin and wait for a fix for now. It will be fixed eventually but as you can tell Tyler is very busy.

**Comment by Logan7432** [comment]
@Megabyte918 Darn, this stinks! That leader board plugin is awesome.

**Comment by Tyler3D** [comment]
@Logan7432 @ToporBigBots I have to rewrite all of the plugins to make them compatible with the new verison

**Comment by Logan7432** [comment]
@Tyler3D Ok!

**Comment by ToporBigBots** [comment]
@Tyler3D Okey!

**Comment by Logan7432** [comment]
@Tyler3D Can you try and fix the LeaderBoard plugin soon as you get time?
